# Generated by Django 4.2.1 on 2023-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('bi-briefcase', 'bi bi-briefcase'), ('bi-card-checklist', 'bi-card-checklist'), ('bi-bar-chart', 'bi bi-bar-chart'), ('bi-binoculars', 'bi bi-binoculars'), ('bi-brightness-high', 'bi bi-brightness-high'), ('bi-calendar4-week', 'bi bi-calendar4-week')], max_length=80)),
            ],
        ),
    ]
