# Generated by Django 4.2.1 on 2023-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('birthday', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
